# Generated by Django 5.1.6 on 2025-02-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_community_tag_post_posttag_userincommunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
